### ISSUE TITLE
NestedScrollView

### ISSUE THREAD

**Issue by bizzguy** [rubensousa/RecyclerViewNestedExample#1]
Great article.  However, I'm having problems getting it to work for me.  My parent view is a NestedScrollView which seems to intercept the "action move" events.  Do you happen to have an Orientation Aware Scroll View?  Thanks.

**Comment by rubensousa** [comment]
You can extend from NestedScrollView and override the onInterceptTouchEvent too. I'm not 100% sure, but check the source code for guidance.
